sudo: required
services:
  - docker

before_install:
  - docker build -t donron/docker-react -f Dockerfile.dev .

script:
 - docker run donron/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket name: "elasticbeanstalk-us-east-2-138577344593"
  bucket path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  